module.exports = {
    'f_':                require('./f_'),
    'f_key':             require('./f_key'),
    'f_ref':             require('./f_ref'),
    'f_head':            require('./f_head'),
    'f_next':            require('./f_next'),
    'f_path':            require('./f_path'),
    'f_prev':            require('./f_prev'),
    'f_tail':            require('./f_tail'),
    'f_parent':          require('./f_parent'),
    'f_context':         require('./f_context'),
    'f_version':         require('./f_version'),
    'f_abs_path':        require('./f_abs_path'),
    'f_ref_index':       require('./f_ref_index'),
    'f_refs_length':     require('./f_refs_length'),
    'f_invalidated':     require('./f_invalidated'),
    'f_wrapped_value':   require('./f_wrapped_value'),
    'f_meta_data':       require('./f_meta_data'),
    'f_meta_path':       require('./f_meta_path'),
    'f_meta_keys':       require('./f_meta_keys'),
    'f_meta_version':    require('./f_meta_version'),
    'f_meta_abs_path':   require('./f_meta_abs_path'),
    'f_meta_deref_to':   require('./f_meta_deref_to'),
    'f_meta_deref_from': require('./f_meta_deref_from'),
};
